### ISSUE TITLE
build script failing on bootstrap.py

### ISSUE THREAD

**Issue by jcblw** [atom/electron-starter#72]
hey yo,

So I'm having some issues running the build script `script/build` on OSX 10.10.2.

Python version: 2.7.9 ( just updated from 2.7.6 )
Node version: 0.12.2 ( tried 1.2.0, 1.7.1, 0.10.36 )

Everything seems to run correctly till this.

```shell
>> Running: python script/bootstrap.py
>> Traceback (most recent call last):
>>   File "script/bootstrap.py", line 131, in <module>
>>     sys.exit(main())
>>   File "script/bootstrap.py", line 36, in main
>>     update_atom_modules('spec')
>>   File "script/bootstrap.py", line 89, in update_atom_modules
>>     execute_stdout([apm, 'install'])
>>   File "/private/var/folders/b7/1fytz8751554gctf2b5y7kzh0000gp/T/eightoheight-build/atom-shell/script/lib/util.py", line 154, in execute_stdout
>>     execute(argv)
>>   File "/private/var/folders/b7/1fytz8751554gctf2b5y7kzh0000gp/T/eightoheight-build/atom-shell/script/lib/util.py", line 142, in execute
>>     raise e
>> subprocess.CalledProcessError: Command '['/private/var/folders/b7/1fytz8751554gctf2b5y7kzh0000gp/T/eightoheight-build/atom-shell/node_modules/.bin/apm', 'install']' returned non-zero exit status 133
>> Rigging atom.gyp to have correct name
Reading /var/folders/b7/1fytz8751554gctf2b5y7kzh0000gp/T/eightoheight-build/atom-shell/atom.gyp...OK
Writing /var/folders/b7/1fytz8751554gctf2b5y7kzh0000gp/T/eightoheight-build/atom-shell/atom.gyp...OK
>> Running: python script/bootstrap.py
>> Traceback (most recent call last):
>>   File "script/bootstrap.py", line 131, in <module>
>>     sys.exit(main())
>>   File "script/bootstrap.py", line 36, in main
>>     update_atom_modules('spec')
>>   File "script/bootstrap.py", line 89, in update_atom_modules
>>     execute_stdout([apm, 'install'])
>>   File "/private/var/folders/b7/1fytz8751554gctf2b5y7kzh0000gp/T/eightoheight-build/atom-shell/script/lib/util.py", line 154, in execute_stdout
>>     execute(argv)
>>   File "/private/var/folders/b7/1fytz8751554gctf2b5y7kzh0000gp/T/eightoheight-build/atom-shell/script/lib/util.py", line 142, in execute
>>     raise e
>> subprocess.CalledProcessError: Command '['/private/var/folders/b7/1fytz8751554gctf2b5y7kzh0000gp/T/eightoheight-build/atom-shell/node_modules/.bin/apm', 'install']' returned non-zero exit status 133
```

**Comment by ChrisMcKenzie** [comment]
do you have pyobjc installed?

**Comment by paulcbetts** [comment]
You shouldn't need pyobjc, I fixed that. Here's what you need to do:

1. Install node 0.10.36
1. `git clean -xdf` to delete your node modules
1. Delete `$TMPDIR/eightoheight-build`
1. Bootstrap and build

Then it'll work

**Comment by jcblw** [comment]
cool that worked thanks @paulcbetts and @ChrisMcKenzie
