### ISSUE TITLE
New build fails

### ISSUE THREAD

**Issue by bsr203** [atom/electron-starter#75]
current version of this package fails at the build step. Is it because `build-atom-shell'` task still refer to old repo?

```
'build-atom-shell':
      tag: "v0.24.0"
      nodeVersion: '0.24.0'
      remoteUrl: "https://github.com/atom/atom-shell"
      buildDir: buildDir
      rebuildPackages: true
      projectName: pkgName
      productName: productName
``` 

```
electron-starter] [master] $ script/build
Node: v0.10.33
npm: v1.4.28
Installing build modules...
Installing apm...
Installing modules ✓
Deduping modules ✓
Running "build-atom-shell" task
>> Cloning into 'vendor/breakpad'...
>> Cloning into 'src'...
>> Cloning into 'vendor/brightray'...
>> Cloning into 'vendor/google-styleguide'...
>> Cloning into 'vendor/gyp'...
>> Cloning into 'vendor/libchromiumcontent'...
>> Cloning into 'vendor/depot_tools'...
>> Cloning into 'vendor/python-patch'...
>> Cloning into 'vendor/depot_tools'...
>> Cloning into 'vendor/native_mate'...
>> Cloning into 'vendor/node'...
>> error: RPC failed; result=56, HTTP code = 200
>> fatal: The remote end hung up unexpectedly
>> fatal: early EOF
>> fatal: index-pack failed
>> Clone of 'https://github.com/atom/node.git' into submodule path 'vendor/node' failed
>> Traceback (most recent call last):
>>   File "script/bootstrap.py", line 142, in <module>
>>     sys.exit(main())
>>   File "script/bootstrap.py", line 28, in main
>>     update_submodules()
>>   File "script/bootstrap.py", line 70, in update_submodules
>>     execute_stdout(['git', 'submodule', 'update', '--init', '--recursive'])
>>   File "/private/var/folders/fc/k8b9ds214nv4lqv2x4395khc0000gn/T/eightoheight-build/atom-shell/script/lib/util.py", line 152, in execute_stdout
>>     raise e
>> subprocess.CalledProcessError: Command '['git', 'submodule', 'update', '--init', '--recursive']' returned non-zero exit status 1
```

**Comment by bsr203** [comment]
how long `script/build` takes to finish? When I ran second time, I waited for 20 mins, and it never proceed after 

```

Installing build modules...
Installing apm...
Installing modules ✓
Deduping modules ✓
Running "build-atom-shell" task

```

will try fresh install again as I suspect initial issue might have due to network (The remote end hung up unexpectedly)

**Comment by bsr203** [comment]
this is crazy, it is 40 mins now with a fresh clone of this repo. and no output after `Running "build-atom-shell" task`

may be because `script/build` didn't finish yet, `script/run` gives below error

```
script/run
Running: /var/folders/fc/k8b9ds214nv4lqv2x4395khc0000gn/T/eightoheight-build/EightOhEight.app/Contents/MacOS/EightOhEight -r .

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1001:11)
    at Process.ChildProcess._handle.onexit (child_process.js:792:34)
```

**Comment by bsr203** [comment]
After an hour, it errored out saying no space. I only had about 2 GB left, and I could see it taking up all the space. Why it takes this long and this much space? will try again freeing up some space :-(

**Comment by bsr203** [comment]
No luck :-(  made enough space, and waited for couple of hours. Not sure how to build the binary and how to run the default app. Any help appreciated. thanks

I am on Mac OSX 10.9.5

**Comment by bsr203** [comment]
with, verbose log.
```
Running "build-atom-shell" task
Verifying properties build-atom-shell.buildDir, build-atom-shell.tag, build-atom-shell.projectName, build-atom-shell.productName exist in config...OK
>> Running: git remote set-url origin https://github.com/atom/atom-shell
>> Running: git fetch origin
>> Running: git reset --hard HEAD
>> Running: git checkout v0.24.0
>> Rigging atom.gyp to have correct name
Reading /var/folders/fc/k8b9ds214nv4lqv2x4395khc0000gn/T/eightoheight-build/atom-shell/atom.gyp...OK
Writing /var/folders/fc/k8b9ds214nv4lqv2x4395khc0000gn/T/eightoheight-build/atom-shell/atom.gyp...OK
>> Running: python script/bootstrap.py -v
>> fatal: Needed a single revision
>> Unable to find current revision in submodule path 'vendor/brightray/vendor/libchromiumcontent'
>> Cloning into 'vendor/depot_tools'...
>> Cloning into 'vendor/native_mate'...
>> Cloning into 'vendor/node'...
>> Failed to recurse into submodule path 'vendor/brightray'
>> Traceback (most recent call last):
>>   File "script/bootstrap.py", line 142, in <module>
>>     sys.exit(main())
>>   File "script/bootstrap.py", line 28, in main
>>     update_submodules()
>>   File "script/bootstrap.py", line 70, in update_submodules
>>     execute_stdout(['git', 'submodule', 'update', '--init', '--recursive'])
>>   File "/private/var/folders/fc/k8b9ds214nv4lqv2x4395khc0000gn/T/eightoheight-build/atom-shell/script/lib/util.py", line 152, in execute_stdout
>>     raise e
>> subprocess.CalledProcessError: Command '['git', 'submodule', 'update', '--init', '--recursive']' returned non-zero exit status 1
>> Rigging atom.gyp to have correct name
Reading /var/folders/fc/k8b9ds214nv4lqv2x4395khc0000gn/T/eightoheight-build/atom-shell/atom.gyp...OK
Writing /var/folders/fc/k8b9ds214nv4lqv2x4395khc0000gn/T/eightoheight-build/atom-shell/atom.gyp...OK
>> Running: python script/bootstrap.py -v
```

**Comment by bsr203** [comment]
I changed the `remoteUrl`, still it stuck

```
Running "build-atom-shell" task
Verifying properties build-atom-shell.buildDir, build-atom-shell.tag, build-atom-shell.projectName, build-atom-shell.productName exist in config...OK
>> Running: git remote set-url origin https://github.com/atom/electron
>> Running: git fetch origin
>> Running: git reset --hard HEAD
>> Running: git checkout v0.24.0
>> Rigging atom.gyp to have correct name
Reading /var/folders/fc/k8b9ds214nv4lqv2x4395khc0000gn/T/eightoheight-build/atom-shell/atom.gyp...OK
Writing /var/folders/fc/k8b9ds214nv4lqv2x4395khc0000gn/T/eightoheight-build/atom-shell/atom.gyp...OK
>> Running: python script/bootstrap.py -v
```

**Comment by bsr203** [comment]
digging further, it tries to download `libchromiumcontent-static.zip`, which is 1.7GB !!

**Comment by bsr203** [comment]
once freed up the sapce, getting another error. Cloned to a new directory, and getting errors in the beginning. will raise another.
